/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Find total products by category
SELECT 
	category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;


-- What is the total revenue generated for each category?
SELECT 
	P.category,
	SUM(S.sales_amount) AS total_revenue
FROM gold.fact_sales S
LEFT JOIN gold.dim_products P
	ON P.product_key = S.product_key
GROUP BY P.category
ORDER BY total_revenue DESC;


-- Find total revenue is generated by each customer
SELECT 
	C.customer_key,
	C.first_name,
	C.last_name,
	SUM(S.sales_amount) AS total_revenue_by_customer
FROM gold.fact_sales S
LEFT JOIN gold.dim_customers C
	ON C.customer_key = S.customer_key
GROUP BY 
	C.customer_key,
	C.first_name,
	C.last_name
ORDER BY total_revenue_by_customer DESC;


-- What is the distribution of sold items across countries?
SELECT 
	C.country,
	SUM(S.quantity) AS total_sold_items
FROM gold.fact_sales S
LEFT JOIN gold.dim_customers C
	ON C.customer_key = S.customer_key
GROUP BY C.country
ORDER BY total_sold_items DESC;


-- What is the distribution of revenue across countries?
SELECT 
	C.country,
	SUM(S.sales_amount) AS total_revenue_by_country
FROM gold.fact_sales S
LEFT JOIN gold.dim_customers C
	ON C.customer_key = S.customer_key
GROUP BY C.country
ORDER BY total_revenue_by_country DESC;